feature: add menu Sound Effects
PurpleBananass/Invaders-SDP pull request #48
Opened 2024-10-04 01:19 UTC by yeyoungyun

### **Feature**
- add sound effects "menuMove" to TitleScreen, GameSettingScreen
- add sound effects "menuClick" to TitleScreen, GameSettingScreen
- add sound effects "menuBack" to GameSettingScreen, AchievementScreen
- add sound effects "nameTyping" to GameSettingScreen
----------------------------------------
- add those 4 sound files to the "res/sound/SFX"

2024-10-04 07:01 UTC, logpacket commented on src/engine/Core.java
> +		SoundManager.getInstance();
You can use member to store singleton reference.
Please refer this code.
멤버 변수를 사용하여 싱글톤 참조를 저장할 수 있습니다.
아래 코드를 참고하세요.
```java
private final SoundManager soundManager = SoundManager.getInstance();
```
This code did not create more instance. just initialize singleton instance. and return that instance's reference
이 코드는 더 많은 인스턴스를 생성하지 않았습니다. 싱글톤 인스턴스를 초기화하고 해당 인스턴스의 참조를 반환합니다.

2024-10-04 07:01 UTC, logpacket commented on src/engine/Core.java
> +		SoundManager.getInstance().closeAllSounds();
Following above code, you can use this code
만약 위의 코드를 따라했다면, 당신은 이 코드를 사용할 수 있습니다.
```java
soundManager.closeAllSounds();
```

2024-10-04 07:01 UTC, logpacket commented on src/engine/Core.java
> +	public static SoundManager getSoundManager() {
Why you need this code?
If you want to use `SoundManager` on the other code, you can use `SoundManager.getInstance()`
왜 이코드가 필요한가요? `SoundManager`사용을 원할 때 `SoundManager.getInstance()`를 사용할 수 있습니다.

2024-10-04 07:01 UTC, logpacket commented on src/engine/SoundManager.java
> +    public void loadSound(String soundName, String filePath) throws IOException, UnsupportedAudioFileException, LineUnavailableException {
You can use enum.
The change reason is string key access can occur typo issue.

Please refer this code.
```java
// Sounds.java

public enum Sounds {
    MENU_BACK("menuBack"),
    MENU_CLICK("menuClick"),
    MENU_MOVE("menuMove"),
    MENU_TYPING("menuTyping");
    
    private final String label;
    
    Sounds(String label) {
        this.label = label;
    }
    
    public String getLabel() {
        return this.label;
    }
}

// SoundManager.java

public void loadSound(Sounds sound, String filePath) throws IOException, UnsupportedAudioFileException, LineUnavailableException {
    ...
    soundClips.put(sound, clip)
}

// *Screen.java
SoundManager soundManager = SoundManger.getInstance();
...

soundManager.playSound(Sounds.MENU_BACK);
```

2024-10-04 16:01 UTC, PIut0 requested changes
사운드 장치가 없을경우 프로그램을 실행할 수 없는 상태입니다. 해당 상황에 대한 예외처리가 필요할 것 같습니다.
The program cannot run if there is no sound device. You probably need to throw an exception for this situation.

```[INFO|12:50:17]: Started loading sound resources. 
Exception in thread "main" java.lang.IllegalArgumentException: No line matching interface Clip supporting format PCM_SIGNED unknown sample rate, 16 bit, stereo, 4 bytes/frame, big-endian is supported.
	at java.desktop/javax.sound.sampled.AudioSystem.getLine(AudioSystem.java:425)
	at java.desktop/javax.sound.sampled.AudioSystem.getClip(AudioSystem.java:461)
	at engine.SoundManager.loadSound(SoundManager.java:75)
	at engine.SoundManager.<init>(SoundManager.java:34)
	at engine.SoundManager.getInstance(SoundManager.java:56)
	at engine.Core.main(Core.java:99)
```

추가로 @logpacket 님께서 Code의 Convention및  품질에 대한 Comment를 잘 달아주셨습니다. 오류 수정과 더불어 해당 내용도 같이 수정되면 좋을것 같습니다 :)
Additionally, @logpacket made a nice comment about the conventions and quality of the code. It would be nice to see those fixed along with the error fixes :)

2024-10-05 05:59 UTC, PIut0 commented on src/screen/AchievementScreen.java
> +import engine.Sound;
engine.Sound 를 참조할 수 없다고 나옵니다. 확인 부탁드리겠습니다.
It says engine.Sound cannot be referenced, can you please check?

2024-10-05 07:27 UTC, logpacket requested changes
I can't found Sound.java. please add that file to this PR
`Sound.java` 파일을 찾을수 없습니다. 이 PR에 해당 파일을 추가해주세요

2024-10-05 12:16 UTC, logpacket approved these changes

2024-10-05 16:17 UTC, PIut0 approved these changes
LGTM :)

2024-10-06 01:11 UTC, merged