feat: Add items
PurpleBananass/Invaders-SDP pull request #70
Opened 2024-10-10 01:03 UTC by dev-moonsc

## Feature
---
- Add Bomb item
- Add Line-Bomb item
- Add Ghost item
- Add Barrier item
- Add Time-Stop item
- Add Multi-Shot item
## Notes
---
_During the development of Bomb and Line-Bomb, modifications were made to the EnemyShipFormation file. The previous code optimized performance by removing destroyed enemies, but this caused issues in implementing items when the array’s original structure wasn’t maintained. Therefore, we changed the approach to set destroyed enemies to null instead of removing them._

2024-10-10 06:02 UTC, yeyoungyun approved these changes

2024-10-10 06:02 UTC, yeyoungyun commented on src/entity/Ship.java
> +                soundManager.playSound(Sound.PLAYER_LASER);
LGTM
다만 멀티샷을 위해 playSound("Sound.PLAYER_LASER")메소드가 여러 번 작성되어있는데 실제 게임 실행 시에는 동시에 재생되어 하나로 들리므로 멀티샷 효과음은 이후 사운드 팀에서 아이템 SFX 추가 시 따로 수정하겠습니다.
However, the playSound("Sound.PLAYER_LASER") method is written multiple times for multi-shot, but when the actual game is run, it is played simultaneously and is heard as one, so the multi-shot sound will be modified separately when adding item SFX in the future.

2024-10-10 08:57 UTC, logpacket commented on src/engine/ItemManager.java
> +            switch (rand.nextInt(6)) {
How about this?
```java
itemTypes = ItemType.values();
this.itemType = itemTypes[rand.nextInt(6)];
```

2024-10-10 08:57 UTC, logpacket commented on src/entity/EnemyShipFormation.java
Why you change null-safe code to nullable code?

2024-10-10 10:53 UTC, dev-moonsc commented on src/entity/EnemyShipFormation.java
Please check the Notes section of the PR message. I know this is not the best way, but since the goal is implementation, We used the most intuitive way. This is not the final code, and We are trying to find better ways.

2024-10-10 11:06 UTC, idealtrue0 commented
Can I see the in-game item usage screen? Blocks that block friendly bullets and allow enemy bullets to pass through have been created in random locations, so it's worth looking into (especially on the barrier side).

게임 내 아이템 사용 화면을 볼 수 있나요? 아군의 총알은 막고 적의 총알은 통과시키는 블록을 적과 아군 사이 중 무작위 위치에 생성하였으니 살펴볼 필요가 있습니다.(특히 베리어쪽에 대해서)

2024-10-10 11:35 UTC, logpacket commented on src/entity/EnemyShipFormation.java
Sorry, I missed that.  I'll try to find a solution to this problem as well.

2024-10-11 03:38 UTC, idealtrue0 requested changes
Please change the information below

2024-10-11 03:38 UTC, idealtrue0 commented on src/engine/ItemManager.java
> +        int screenWidth = 448;
2차 회의에서 정했던 대로 screenWidth를 448이 아닌 600으로 할 예정입니다. 수정 부탁드립니다.


As decided in the second meeting, the screenWidth will be set to 600 instead of 448. Please correct it.

2024-10-11 03:38 UTC, idealtrue0 commented on src/engine/ItemManager.java
> +        int screenWidth = 448;
높이 또한 650이니 참고 부탁드립니다!

The height is also 650, so please keep that in mind!

2024-10-11 03:50 UTC, logpacket commented on src/engine/ItemManager.java
> +        int screenWidth = 448;
It would be nice to have this managed as a constant.

이 값은 상수로 관리되는 편이 좋을 것 같습니다.

2024-10-11 12:38 UTC, dev-moonsc commented
> Can I see the in-game item usage screen? Blocks that block friendly bullets and allow enemy bullets to pass through have been created in random locations, so it's worth looking into (especially on the barrier side).
> 
> 게임 내 아이템 사용 화면을 볼 수 있나요? 아군의 총알은 막고 적의 총알은 통과시키는 블록을 적과 아군 사이 중 무작위 위치에 생성하였으니 살펴볼 필요가 있습니다.(특히 베리어쪽에 대해서)

I have attached a screenshot of the barrier item to the main text. Please check it.

2024-10-11 13:18 UTC, idealtrue0 commented
> > Can I see the in-game item usage screen? Blocks that block friendly bullets and allow enemy bullets to pass through have been created in random locations, so it's worth looking into (especially on the barrier side).
> > 게임 내 아이템 사용 화면을 볼 수 있나요? 아군의 총알은 막고 적의 총알은 통과시키는 블록을 적과 아군 사이 중 무작위 위치에 생성하였으니 살펴볼 필요가 있습니다.(특히 베리어쪽에 대해서)
> 
> I have attached a screenshot of the barrier item to the PR message. Please check it.

I confirmed the photo. Please check the changes to the barrier width above.

2024-10-11 20:33 UTC, dev-moonsc commented on src/entity/Ship.java
> +                soundManager.playSound(Sound.PLAYER_LASER);
Ok. I modified to call playSound once.

2024-10-11 20:34 UTC, dev-moonsc commented on src/engine/ItemManager.java
> +            switch (rand.nextInt(6)) {
Ok. I modified it. Thanks :)

2024-10-11 20:34 UTC, dev-moonsc commented on src/engine/ItemManager.java
> +        int screenWidth = 448;
I modified it. Thanks :)

2024-10-11 23:15 UTC, idealtrue0 approved these changes
LGTM. Please synchronize with master.

2024-10-11 23:58 UTC, merged