Add ship switch setting to game settings, add new special enemy (diver) & add different bullets for each ship
PurpleBananass/Invaders-SDP pull request #87
Opened 2024-10-17 05:45 UTC by brewcoua

This PR adds a few new features:
- Moved the ship switch setting to the game settings screen and rework it to show ship design and stats
![Screenshot from 2024-10-17 14-36-24](https://github.com/user-attachments/assets/c2abb418-be8d-4625-baaa-8c03315cd9f7)
- Add a new special enemy: Diver
  It dives down once every few seconds, trying to hit the player.
![Screenshot from 2024-10-17 14-36-48](https://github.com/user-attachments/assets/2c0b8133-1c49-40e8-9775-adcd3369b266)
- Add different bullets (sprite and color) for each ship

This also fixes an issue with the bomb that caused an index out of bounds error (within the `operateBomb` method in `ItemManager`, adding an extra check for the array size), and another issue with multiple audio streams being opened when loading a sound in the `SoundManager`.

2024-10-22 03:52 UTC, dev-moonsc requested changes
Ship switch setting is working well. However, In-game issues are occurred by modifying EnemyShipFormation.

2024-10-22 03:52 UTC, dev-moonsc commented on src/entity/EnemyShipFormation.java
Since EnemyShipGrid(previously EnemyShips) was modified to cleanup formation by removing destroyed ships, IndexOutOfBoundsException can be occurred during bomb & line-bomb operations. Please check #70. EnemyShipFormation need to maintain its original formation matrix.

2024-10-22 05:58 UTC, logpacket requested changes
I haven't had any issues in 2-player mode, but like the comment above, I get an `IndexOutOfBounds` error when using bomb items.

2024-10-22 06:26 UTC, brewcoua commented
> I haven't had any issues in 2-player mode, but like the comment above, I get an `IndexOutOfBounds` error when using bomb items.

Could you give me specifically where the error occurs ? Like a specific line or something

2024-10-22 07:00 UTC, dev-moonsc commented
> > I haven't had any issues in 2-player mode, but like the comment above, I get an `IndexOutOfBounds` error when using bomb items.
> 
> Could you give me specifically where the error occurs ? Like a specific line or something

Here's the error message.
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:365)
	at java.base/java.util.ArrayList.get(ArrayList.java:428)
	at engine.ItemManager.operateLineBomb(ItemManager.java:230)
	at engine.ItemManager.useItem(ItemManager.java:130)
	at screen.GameScreen.manageCollisions(GameScreen.java:878)
	at screen.GameScreen.update(GameScreen.java:481)
	at screen.Screen.run(Screen.java:87)
	at screen.GameScreen.run(GameScreen.java:321)
	at engine.Frame.setScreen(Frame.java:59)
	at engine.Core.main(Core.java:128)

Process finished with exit code 0
```

2024-10-22 07:03 UTC, brewcoua commented
Alright, the commit above should have fixed the issue. I added an additional size check as, since ships are now being cleaned up as they are destroyed, the rows may not have the same size anymore.

2024-10-22 07:04 UTC, brewcoua commented on src/entity/EnemyShipFormation.java
This should be fixed.

2024-10-22 07:38 UTC, dudghks commented
This commit modifies EnemyShipFormation so that EnemyShipFormation maintains its original formation matrix. This should fix the issues with the bomb.

2024-11-04 04:59 UTC, dev-moonsc approved these changes
LGTM :)

2024-11-14 01:42 UTC, closed without merging